# Analyse Exploratoire des Données Filtrées

Ce Notebook contient une analyse exploratoire des données après la phase de pré-filtration (`filtered_data`).

Nous allons examiner les caractéristiques principales des données, visualiser les répartitions et identifier les tendances pertinentes.

In [1]:
# Importer les bibliothèques nécessaires
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# Définir le chemin du fichier filtered_data\n",
filtered_data_path = '../data/processed/filtered_data.csv'

# Charger filtered_data\n",
filtered_data = pd.read_csv(filtered_data_path)
filtered_data.head()

,DATE_OF_THE_DAY,SIM_NUMBER,HAS_USED_MOB_MONEY_IN_LAST_30_DAYS,HAS_USED_MOB_MONEY_IN_LAST_7_DAYS,HAS_USED_MOB_MONEY_IN_LAST_90_DAYS,PAID_DATA_VOLUME,PAID_VOICE_TRAFFIC,HAS_USED_MOB_MONEY_IN_LAST_1_DAY,VOICE_REVENUE,DATA_REVENUE,...,MOB_MONEY_ACCOUNT_AMOUNT,TOTAL_LOADING_MONEY_IN_MOB_MONEY,TOTAL_CASHOUT_MOB_MONEY_ACCOUNT,TOTAL_CASHOUT_MOB_MONEY_FOR_package_PURCHASE,TOTAL_CASHOUT_MOB_MONEY_TRANSFER_MONEY,REGISTRATION_STATUS,age,REGION,tenure_years,CUST_CATEGORY
0,20240110,C909154549,0,1,1,1952.76,1488.73,0,110.71,63.39,...,5347.49,1219.70,1017.45,861.16,940.19,Accepted,41,Washington,2,Business
1,20240809,C1185358096,1,1,1,2737.16,157.62,0,486.90,97.69,...,1689.84,1707.61,1082.82,1949.25,629.66,Accepted,29,Illinois,2,Individual
2,20231213,C135396218,1,1,1,1091.28,1679.70,0,95.44,164.40,...,9633.66,1939.06,3822.66,1322.70,78.83,Accepted,58,Colorado,2,Individual
3,20240110,C1225067641,1,1,1,2672.49,1828.85,1,183.03,162.72,...,3197.23,3355.79,1370.23,608.61,358.89,Accepted,35,Kansas,2,Business
4,20230515,C444372421,1,0,1,4223.31,1915.18,1,332.88,101.68,...,8717.81,1426.07,3506.71,78.90,2294.62,Accepted,55,South Dakota,2,Individual

In [8]:
# Afficher les informations générales\n",
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351162 entries, 0 to 351161
Data columns (total 84 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   DATE_OF_THE_DAY                               351162 non-null  int64
 1   SIM_NUMBER                                    351162 non-null  object
 2   HAS_USED_MOB_MONEY_IN_LAST_30_DAYS            351162 non-null  int64
 3   HAS_USED_MOB_MONEY_IN_LAST_7_DAYS             351162 non-null  int64
 4   HAS_USED_MOB_MONEY_IN_LAST_90_DAYS            351162 non-null  int64
 5   PAID_DATA_VOLUME                              351162 non-null  float64
 6   PAID_VOICE_TRAFFIC                            351162 non-null  float64
 7   HAS_USED_MOB_MONEY_IN_LAST_1_DAY              351162 non-null  int64
 8   VOICE_REVENUE                                 351162 non-null  float64
 9   DATA_REVENUE                                  351162 non-null  float64
 10  SMS_REVENUE                                   351162 non-null  float64
 11  DIGITAL_REVENUE                               351162 non-null  float64
 12  MOB_MONEY_REVENUE                             351162 non-null  float64
 13  FREE_VOICE_TRAFFIC                            351162 non-null  float64
 14  FREE_DATA_VOLUME                              351162 non-null  float64
 15  VOICE_TRAFFIC_ONNET                           351162 non-null  float64
 16  VOICE_TRAFFIC_OFFNET                          351162 non-null  float64
 17  NB_CALLS_EMITTED_ONNET                        351162 non-null  int64
 18  NB_CALLS_RECEIVED_ONNET                       351162 non-null  int64
 19  NB_CALLS_EMITTED_OFFNET                       351162 non-null  int64
 20  NB_CALLS_RECEIVED_OFFNET                      351162 non-null  int64
 21  IS_RGS_1                                      351162 non-null  int64
 22  IS_RGS_7                                      351162 non-null  int64
 23  IS_RGS_30                                     351162 non-null  int64
 24  IS_RGS_90                                     351162 non-null  int64
 25  NB_CALLS_EMITTED_INTERNATIONAL                351162 non-null  int64
 26  NB_CALLS_RECEIVED_INTERNATIONAL               351162 non-null  int64
 27  VOICE_OUTGOING_TRAFFIC_INTERNATIONAL          351162 non-null  float64
 28  VOICE_INCOMING_TRAFFIC_INTERNATIONAL          351162 non-null  float64
 29  VOICE_OUTGOING_TRAFFIC_ONNET                  351162 non-null  float64
 30  VOICE_INCOMING_TRAFFIC_ONNET                  351162 non-null  float64
 31  VOICE_OUTGOING_TRAFFIC_OFFNET                 351162 non-null  float64
 32  VOICE_INCOMING_TRAFFIC_OFFNET                 351162 non-null  float64
 33  NB_VOICE_PACKAGES_SUBSCRIPTIONS               351162 non-null  int64
 34  NB_DATA_PACKAGES_SUBSCRIPTIONS                351162 non-null  int64
 35  VOICE_PACKAGES_REVENUE                        351162 non-null  float64
 36  NB_SMS_SENT_ONNET                             351162 non-null  int64
 37  NB_SMS_SENT_OFFNET                            351162 non-null  int64
 38  NB_SMS_RECEIVED_ONNET                         351162 non-null  int64
 39  NB_SMS_RECEIVED_OFFNET                        351162 non-null  int64
 40  NB_SMS_SENT_INTERNATIONAL                     351162 non-null  int64
 41  NB_SMS_RECEIVED_INTERNATIONAL                 351162 non-null  int64
 42  NB_SMS_PACKAGES_SUBSCRIPTIONS                 351162 non-null  int64
 43  SMS_PACKAGE_REVENUE                           351162 non-null  float64
 44  NB_VOICE_PACKAGES_SUBS_VIA_MOB_MONEY          351162 non-null  int64
 45  NB_VOICE_PACKAGES_SUBS_VIA_POS                351162 non-null  int64
 46  NB_VOICE_PACKAGES_SUBS_VIA_MAIN_ACCOUNT       351162 non-null  int64
 47  NB_DATA_package_SUBS_VIA_MOB_MONEY            351162 non-null  int64
 48  NB_DATA_package_SUBS_VIA_POS                  351162 non-null  int64
 49  NB_DATA_package_SUBS_VIA_MAIN_ACCOUNT         351162 non-null  int64
 50  NB_SMS_package_SUBS_VIA_MOB_MONEY             351162 non-null  int64
 51  NB_SMS_package_SUBS_VIA_POS                   351162 non-null  int64
 52  NB_SMS_package_SUBS_VIA_MAIN_ACCOUNT          351162 non-null  int64
 53  NB_MIXED_package_SUBS_VIA_MOB_MONEY           351162 non-null  int64
 54  NB_MIXED_package_SUBS_VIA_POS                 351162 non-null  int64
 55  NB_MIXED_package_SUBS_VIA_MAIN_ACCOUNT        351162 non-null  int64
 56  IS_SMARTPHONE_USER                            351162 non-null  int64
 57  LAST_EVENT_DATE                               351162 non-null  object
 58  LAST_EVENT_TYPE                               351162 non-null  object
 59  IS_DATA_RGS1                                  351162 non-null  int64
 60  IS_DATA_RGS7                                  351162 non-null  int64
 61  IS_DATA_RGS30                                 351162 non-null  int64
 62  IS_DATA_RGS90                                 351162 non-null  int64
 63  MAIN_ACCOUNT_AMOUNT                           351162 non-null  float64
 64  EXTRA_TIME_LOAN_AMOUNT_RENT                   351162 non-null  float64
 65  EXTRA_TIME_LOAN_AMOUNT_TO_PAY_BACK            351162 non-null  float64
 66  REFILL_MAIN_AMOUNT                            351162 non-null  float64
 67  REFILL_mobile_money_ACCOUNT                   351162 non-null  float64
 68  TOTAL_SPENT_MAIN_ACCOUNT                      351162 non-null  float64
 69  TOTAL_SPENT_MOB_MONEY_ACCOUNT                 351162 non-null  float64
 70  NB_package_GIFTS_SENT                         351162 non-null  int64
 71  NB_package_GIFTS_RECEIVED                     351162 non-null  int64
 72  AMOUNT_package_GIFTS_SENT                     351162 non-null  float64
 73  AMOUNT_package_GIFTS_RECEIVED                 351162 non-null  float64
 74  MOB_MONEY_ACCOUNT_AMOUNT                      351162 non-null  float64
 75  TOTAL_LOADING_MONEY_IN_MOB_MONEY              351162 non-null  float64
 76  TOTAL_CASHOUT_MOB_MONEY_ACCOUNT               351162 non-null  float64
 77  TOTAL_CASHOUT_MOB_MONEY_FOR_package_PURCHASE  351162 non-null  float64
 78  TOTAL_CASHOUT_MOB_MONEY_TRANSFER_MONEY        351162 non-null  float64
 79  REGISTRATION_STATUS                           351162 non-null  object
 80  age                                           351162 non-null  int64
 81  REGION                                        351162 non-null  object
 82  tenure_years                                  351162 non-null  int64
 83  CUST_CATEGORY                                 351162 non-null  object
dtypes: float64(33), int64(45), object(6)
memory usage: 225.0+ MB