# Analyse Exploratoire des Données Filtrées

Ce Notebook contient une analyse exploratoire des données après la phase de pré-filtration (`filtered_data`).

Nous allons examiner les caractéristiques principales des données, visualiser les répartitions et identifier les tendances pertinentes.

In [1]:
# Importer les bibliothèques nécessaires
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Définir le chemin du fichier filtered_data,
filtered_data_path = '../data/processed/filtered_data.csv'

# Charger filtered_data,
filtered_data = pd.read_csv(filtered_data_path)
filtered_data.head()

,DATE_OF_THE_DAY,SIM_NUMBER,HAS_USED_MOB_MONEY_IN_LAST_30_DAYS,HAS_USED_MOB_MONEY_IN_LAST_7_DAYS,HAS_USED_MOB_MONEY_IN_LAST_90_DAYS,PAID_DATA_VOLUME,PAID_VOICE_TRAFFIC,HAS_USED_MOB_MONEY_IN_LAST_1_DAY,VOICE_REVENUE,DATA_REVENUE,...,ID_EXPIRY_DATE,HAS_SIM_NUM_PARENT,REGISTRATION_STATUS,REGISTRATION_TYPE,LANG,IS_MOB_MONEY_MERCHANT,IS_MOB_MONEY_USER,DEVICE_TYPE,age,tenure_years
0,20230918,C1850294050,1,1,1,1551.85,1311.07,1,486.81,115.21,...,2027-05-10 13:23:06.569908,0,Accepted,Existing,English,1,0,Feature phone,59,2
1,20231029,C2042071881,0,1,1,4759.05,267.29,1,77.07,110.88,...,2032-08-27 13:23:06.569908,0,Accepted,Existing,French,0,1,Smartphone,57,2
2,20231102,C1001545517,0,1,1,4813.52,24.33,0,83.86,7.84,...,2031-07-15 13:23:06.569908,0,Accepted,New,French,0,1,Feature phone,59,2
3,20231126,C1204243390,0,1,1,734.09,1018.34,0,284.10,18.31,...,2033-09-07 13:23:06.569908,0,Accepted,New,French,1,0,Smartphone,52,2
4,20230801,C913434705,1,1,1,2166.61,255.10,1,464.50,120.56,...,2027-05-17 13:23:06.569908,1,Accepted,New,French,1,0,Feature phone,46,2

In [3]:
# Afficher les informations générales,
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351748 entries, 0 to 351747
Columns: 103 entries, DATE_OF_THE_DAY to tenure_years
dtypes: float64(33), int64(49), object(21)
memory usage: 276.4+ MB

In [4]:
len(filtered_data.SIM_NUMBER.unique())

351748